services:
  server:
    image: server-nginx
    build:
      dockerfile: ./.docker/Dockerfile
      context: .
    volumes:
      - ./catalog:/usr/share/nginx/html/catalog:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    networks:
      - browser_network

  stac-browser:
    image: stac-browser:v1
    build:
      context: ./stac-browser
    depends_on:
      - server
    ports:
      - "8091:8080"
    environment:
      - SB_catalogUrl=http://localhost/catalog.json
      - SB_catalogTitle="PSUP STAC Browser"
    networks:
      - browser_network

networks:
  browser_network:
